#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

function requires_yii() {
    [ $(jq --raw-output '.require["symfony/symfony"]' < "$BUILD_DIR/composer.json") != "null" ]
}

function sets_framework_yii() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "yii" ]
}

case "$1" in
    detect)
        if [ -f "$BUILD_DIR/composer.json" ] && requires_yii || sets_framework_yii; then
            echo "-----> Detected Yii App"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Installing Yii Site Config"
        cp "$basedir/../conf/nginx/yii.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        ;;
esac
